### ISSUE TITLE
Check marks fail to render properly when CSS reset is present

### ISSUE THREAD

**Issue by pwolfert** [CMSgov/design-system#854] opened 2020-10-19 16:34 UTC
**Describe the bug**
In our application, all checked radio buttons and checkboxes have a single white line instead of a check mark.

The following CSS-reset rule of ours is triggering this behavior:
```css
*,
*:before,
*:after {
  box-sizing: inherit;
}
```

It can be fixed by adding `box-sizing: content-box;` to the `.ds-c-choice+label:after` rule (https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/styles/components/_Choice.scss#L47)

**To Reproduce**
Direct message for instructions to see the bug in a healthcare.gov staging environment.

**Expected behavior**
It should look like a check mark.

**Screenshots**
<img width="175" alt="Screen Shot 2020-10-19 at 9 23 51 AM" src="https://user-images.githubusercontent.com/7595652/96479736-35f3f080-11ee-11eb-94ef-b2180f89501b.png">

**Comment by nichia** [comment] 2020-10-19 17:12
Thanks for submitting this. The issue is tracked here: https://jira.cms.gov/browse/WNMGDS-670

**Comment by bernardwang** [comment] 2020-11-03 17:14
This fix is included in the latest v2.2.0 release. This change will also be included in the next HCgov DS release after [this PR](https://github.com/CMSgov/hcgov-design-system/pull/8) is reviewed and merged

**Closed by bernardwang** 2020-11-03 17:14 UTC
Labels: Bug, In JIRA
