### ISSUE TITLE
Sass compilation errors

### ISSUE THREAD

**Issue by anthony-kopczyk** [CMSgov/design-system#2412] opened 2023-03-09 21:53 UTC
**Describe the bug**

We're upgrading the medicare my SPA to use medicare DS 8. We're using sass to compile styles. When we import @cmsgov/ds-medicare-gov/dist/css/index, we're getting build failures. It looks like to be some kind of syntax error. If we manually replace replace all `*-` with `* -` in the minified index file, the errors resolve and we can build our app again.

```
// Extracted from the index file
.ds-l-row {
  margin-left: calc(var(--grid-gutter-width)*-.5);
  margin-right: calc(var(--grid-gutter-width)*-.5)
}
```

We could import it as a `.css` but we're extending classes through our app quite a bit and it's a large refactor for us to handle right now.

**To Reproduce**

In a sass compilation, import @cmsgov/ds-medicare-gov/dist/css/index on build.

**Expected behavior**

When importing @cmsgov/ds-medicare-gov/dist/css/index we shouldn't receive compilation errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows and OS X
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Additional context**

We're currently using v4 of react-scripts on our app. We're not sure if an upgrade to 5 would resolve this, but like removing extends in our css, upgrading to react-scripts 5 requires a few things that would be pretty large for us to handle right now. If that's a root cause though we can look at reprioritizing or reordering some of these upgrades.

**Comment by pwolfert** [comment] 2023-03-09 22:24
@anthony-kopczyk, thanks for letting us know. Could you share the exact error you're getting? Is Sass having trouble understanding that it's a multiplication expression without the space? And could you tell us what version of Sass you're using?

**Comment by anthony-kopczyk** [comment] 2023-03-09 22:43
When we import into our javascript we get the same error, so I don't think it's the sass compiling itself. Our sass is set to ^1.53.0, which looks like it's the same as the DS.

```
import '@cmsgov/ds-medicare-gov/dist/css/index.css';
```

The exact error looks like postcss is unable to load the css file. 
```
ERROR in ./node_modules/@cmsgov/ds-medicare-gov/dist/css/index.css (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-4-1!./node_modules/react-scripts/node_modules/postcss-loader/src??postcss!./node_modules/@cmsgov/ds-medicare-gov/dist/css/index.css)
Module build failed (from ./node_modules/react-scripts/node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 31
    at .../node_modules/@cmsgov/ds-medicare-gov/dist/css/index.css:1:39006
    at Parser.error (.../node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (.../node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (.../node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (.../node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (.../node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (.../node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at .../node_modules/postcss-custom-properties/index.cjs.js:333:24
    at .../node_modules/postcss/lib/container.js:194:18
    at .../node_modules/postcss/lib/container.js:139:18
    at Rule.each (.../node_modules/postcss/lib/container.js:105:16)
```

Our version of postcss is 7.0.39, while it looks like the design system is using 8. I don't see any breaking changes listed in the postcss changelog.

**Comment by pwolfert** [comment] 2023-03-10 00:51
@anthony-kopczyk, I have [modified one of our examples](https://github.com/CMSgov/design-system/compare/pwolfert/troubleshooting-medicare?expand=1) to...

1. Import the `ds-medicare-gov` styles within a Sass file _as Sass_ and not as CSS
2. Backtrack to a version of `react-scripts` that uses WebPack 4 and Postcss `7.0.39`

Unfortunately this didn't reproduce the error, though. While we still don't know _why_ this is happening, it doesn't change the fact that it is. If you were to reverse the order of the operands, would it give the same error? I think the following regex should work to flip them all in that minifed CSS file:

```
search: `calc\((var\([a-z\-]*\))\*-(.*?)\)`
replace: `calc(-$2*$1)`
```

That replace pattern is what the search and replace tool in vscode expects. I'm not sure how universal that is.

**Comment by forrestbaer** [comment] 2023-03-10 15:15
Do you have a postcss configuration you could share? It looks like versions 7.x.x of postcss required a config?

**Comment by forrestbaer** [comment] 2023-03-13 16:36
I found [this issue](https://github.com/postcss/postcss-custom-properties/issues/161#issuecomment-479025016) which seems similar, which is what makes me wonder if one of the `postcss` dependencies needs upgrading as well.

**Comment by forrestbaer** [comment] 2023-03-30 21:14
Closing!

**Closed by forrestbaer** 2023-03-30 21:14 UTC
