### ISSUE TITLE
Null reference errors on DateField input refs

### ISSUE THREAD

**Issue by scitech** [CMSgov/design-system#543] opened 2019-11-04 15:09 UTC
**Describe the bug**

We're seeing a lot of errors like `Cannot read property ‘value’ of null` in New Relic.

**To Reproduce**

Unsure how to reproduce, I think this is a timing issue -- somehow `formatDate` is called before the month/day/year input refs are available.

**Expected behavior**

`formatDate` should not attempt to access the value property of the input refs when the refs are null.

**Screenshots**

<img width="600" alt="image" src="https://user-images.githubusercontent.com/4130722/68131362-8a6d6580-fee2-11e9-9c80-30508a013dd9.png">

**Desktop (please complete the following information):**

So far seeing this in Chrome/Safari, varying OSes.

**Comment by bernardwang** [comment] 2019-11-04 16:25
Tracked here: https://jira.cms.gov/browse/WNMGDS-297

**Comment by bernardwang** [comment] 2019-11-07 20:12
I was also unable to reproduce, but I merged this commit to prevent accessing of invalid refs.
https://github.com/CMSgov/design-system/commit/97919653e4b2e6aa587cba6fcad4615a0f76e78a

**Closed** 2019-11-08 18:42 UTC
Labels: Bug, In JIRA
